{% set name = "napari-pointslayer-projection" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-pointslayer-projection-{{ version }}.tar.gz
  sha256: 3d3e45d01ef7c2a5672b0cbfff069b4b57c0ee7e1088348d8ace8a71b2aca73b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - magicgui
    - napari
    - numpy
    - python >=3.8,<3.11
    - qtpy

test:
  imports:
    - napari_pointslayer_projection
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gatoniel/napari-pointslayer-projection
  summary: This plugin creates a 2d projection of all your points.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gatoniel
    - goanpeca
    - jaimergp
